FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y  build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
RUN apt-get install -y  libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev

